name: minipress

services:
  sql:
    image: mariadb:11.4
    container_name: minipress_db
    restart: unless-stopped
    env_file:
      - .database.env
    volumes:
      - mdb:/var/lib/mysql
    networks:
      minipress.net:
        aliases:
          - sql.db

  adminer:
    image: adminer:5.4.2
    restart: unless-stopped
    ports:
      - "30000:8080"
    command: php -S 0.0.0.0:8080 -t /var/www/html
    depends_on:
      - sql
    networks:
      - minipress.net

  web:
    image: nginx:1.31.1
    restart: unless-stopped
    ports:
      - "30001:80"
    volumes:
      - "./web/src:/usr/share/nginx/html:ro"
  
  coreadmin:
    build:
      context: core
      dockerfile: ./core.Dockerfile
    restart: unless-stopped
    ports:
      - "30002:80"
    volumes:
      - "./core:/app"
    depends_on:
      - sql
    networks:
      - minipress.net
    working_dir: /app
    command: 'sh -c "composer install && php -S 0.0.0.0:80 -t /app/public/admin"'

  coreapi:
    build:
      context: core
      dockerfile: ./core.Dockerfile
    restart: unless-stopped
    ports:
      - "30003:80"
    volumes:
      - "./core:/app"
    depends_on:
      - sql
    networks:
      - minipress.net
    working_dir: /app
    command: 'sh -c "composer install && php -S 0.0.0.0:80 -t /app/public/api /app/public/api/index.php"'


networks:
  minipress.net:
    driver: bridge

volumes:
  mdb: