version: '3.8'

services:
  sql:
    image: mariadb:latest
    container_name: minipress_db
    env_file:
      - .database_env
    volumes:
      - mdb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      minipress.net:
        aliases:
          - sql.db

  adminer:
    image: adminer
    container_name: minipress
    ports:
      - "8081:8080"
    networks:
      - minipress.net

networks:
  minipress.net:
    driver: bridge

volumes:
  mdb: