delete from articles;
delete from categories;
delete from utilisateurs;

insert into utilisateurs (id, nom, email, mdp, role) values
(1, 'Luca Vidiri', 'Luca.vidiri@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin'),
(2, 'Nacime Laghezali', 'nacime.laghezali@email.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'user');

insert into categories (id, titre, description) values
(1, 'ligue 1', 'toute lactu du championnat de france de football'),
(2, 'ligue des champions', 'les soirées européennes et les chocs de la coupe aux grandes oreilles'),
(3, 'mercato', 'les rumeurs de transferts les officialisations et les négociations');

insert into articles (id, titre, resume, contenu, image_url, est_publie, categorie_id, auteur_id) values
(1, 'le psg domine le classique au velodrome', 'le paris saint germain s est imposé avec la manière face à l olympique de marseille lors du choc de la journée confortant ainsi sa place de leader du championnat face à un rival impuissant.', 'lorem ipsum dolor sit amet consectetur adipiscing elit. cras varius tristique velit id feugiat. proin nec finibus elit. donec nec justo sed velit pretium placerat vitae at purus. quisque tincidunt lectus at lectus laoreet gravida. sed scelerisque mi ligula id porttitor ipsum faucibus et. etiam id ligula tortor. suspendisse potenti. morbi a vulputate massa. integer quis interdum erat sed maximus magna suspendisse tristique accumsan elit ut.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. duis iaculis sollicitudin turpis at sodales. nullam non risus eget elit molestie feugiat. integer ut lacus in turpis consectetur convallis nec a leo. curabitur at urna lorem. morbi porta nisl id nunc pretium finibus. pellentesque placerat erat vel accumsan ultrices. sed eu lorem ex. donec eu leo at nisl sollicitudin consequat ac sed sem. phasellus interdum sapien sed tortor porta rhoncus.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. fusce vulputate tortor finibus eleifend egestas. class aptent taciti sociosqu ad litora torquent per conubia nostra per inceptos himenaeos. dynamic nisl diam eget est pellentesque hendrerit. phasellus sed justo est. cras tempor finibus elementum. proin vel finibus massa. donec efficitur eget ante vitae varius. nullam ac mollis lectus. maecenas feugiat hendrerit nisi sit amet vestibulum ex eleifend id.', 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2', true, 1, 1),

(2, 'les secrets tactiques de la remontada de brest', 'le stade brestois a surpris tout le monde ce week end en inversant la tendance de manière héroïque grâce à des ajustements tactiques précis mis en place à la mi temps.', 'lorem ipsum dolor sit amet consectetur adipiscing elit. suspendisse iaculis tincidunt lorem quis ultrices. nulla facilisi. morbi sed arcu nec ante molestie tempor. curabitur pretium ex vitae mi tempus imperdiet. aliquam elementum interdum ipsum id iaculis. donec interdum accumsan risus nec commodo. vestibulum nec nulla sed diam viverra dictum in pulvinar libero. curabitur molestie leo nec erat pretium semper. proin at justo at risus viverra finibus ac sit amet sem.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. nulla ac diam accumsan ligula tempor cursus ac eget ex. nam ut ante non arcu congue laoreet non id magna. morbi porta eleifend dictum. aliquam rhoncus ex sapien ut convallis arcu facilisis sed. integer ac tempor sem. sed fringilla tempor sem non finibus. nulla sit amet nulla elit. integer imperdiet id libero ut fringilla. etiam rhoncus sapien ipsum vitae feugiat felis viverra ut.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. ut scelerisque elit magna vitae placerat lorem molestie vitae. donec sit amet felis arcu. duis facilisis diam nulla eu consequat felis iaculis eu. integer ut eros lectus. ut rhoncus lectus at nibh maximus tincidunt. phasellus aliquet tellus ac lectus elementum non sollicitudin libero elementum. duis condimentum purus sapien id scelerisque metus cursus eu. sed a nunc facilisis purus suscipit varius eu elementum nibh.', 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c', true, 1, 1),

(3, 'real madrid la quete d un nouveau sacre', 'le club madrilène aborde la phase finale de la ligue des champions avec de grandes ambitions porté par un collectif huilé et des individualités capables de basculer la rencontre.', 'lorem ipsum dolor sit amet consectetur adipiscing elit. ut luctus ex sed accumsan consequat. proin feugiat elit ac metus congue sit amet luctus eros molestie. sed tristique mi non neque tristique imperdiet. donec tempor finibus ante nec tempus. nulla rhoncus sem vitae purus efficitur aliquet. aenean vel lectus pellentesque tellus vulputate finibus. sed elementum nisl a sem interdum bibendum. fusce imperdiet leo ut turpis egestas ac convallis felis semper. nam eu feugiat justo.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. ut dictum urna tellus vel feugiat ante scelerisque interdum. donec congue arcu a felis facilisis ac tristique ante condimentum. cras ut diam in neque posuere condimentum. pellentesque id lorem sollicitudin ex rutrum tempor interdum ut lorem. integer in eros sed nisl ultrices finibus. donec scelerisque libero tellus vitae facilisis tortor tincidunt et. curabitur nisl sem bibendum quis tellus at finibus tristique sapien.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. morbi efficitur accumsan dui sed pretium. ut pretium leo non purus vehicula rhoncus. integer pellentesque iaculis turpis id condimentum. nam feugiat mollis nisl feugiat viverra. donec scelerisque tincidunt iaculis. curabitur non mi quis ipsum facilisis mattis sit amet quis felis. dynamic sit amet sapien quis urna luctus convallis id sed mi. sed ac tellus ut nunc tristique viverra elementum ut leo.', 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55', true, 2, 1),

(4, 'le choc manchester city bayern tient ses promesses', 'les deux géants européens se sont quittés sur un score de parité après un match d une intensité folle tactiquement parfait et riche en rebondissements pour les supporters.', 'lorem ipsum dolor sit amet consectetur adipiscing elit. donec nec justo sed velit pretium placerat vitae at purus. quisque tincidunt lectus at lectus laoreet gravida. sed scelerisque mi ligula id porttitor ipsum faucibus et. etiam id ligula tortor. suspendisse potenti. morbi a vulputate massa. integer quis interdum erat sed maximus magna suspendisse tristique accumsan elit ut. aliquam elementum interdum ipsum id iaculis.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. duis iaculis sollicitudin turpis at sodales. nullam non risus eget elit molestie feugiat. integer ut lacus in turpis consectetur convallis nec a leo. curabitur at urna lorem. morbi porta nisl id nunc pretium finibus. pellentesque placerat erat vel accumsan ultrices. sed eu lorem ex. donec eu leo at nisl sollicitudin consequat ac sed sem. phasellus interdum sapien sed tortor porta rhoncus.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. ut scelerisque elit magna vitae placerat lorem molestie vitae. donec sit amet felis arcu. duis facilisis diam nulla eu consequat felis iaculis eu. integer ut eros lectus. ut rhoncus lectus at nibh maximus tincidunt. phasellus aliquet tellus ac lectus elementum non sollicitudin libero elementum. duis condimentum purus sapien id scelerisque metus cursus eu. sed a nunc facilisis purus suscipit varius eu elementum nibh.', 'https://images.unsplash.com/photo-1543351611-58f69d7c1781', true, 2, 2),

(5, 'un prodige bresilien en route pour l europe', 'les plus grands clubs du continent s arrachent la nouvelle pépite de santos dont le transfert record devrait être officialisé dans les toutes prochaines heures du marché.', 'lorem ipsum dolor sit amet consectetur adipiscing elit. cras varius tristique velit id feugiat. proin nec finibus elit. donec nec justo sed velit pretium placerat vitae at purus. quisque tincidunt lectus at lectus laoreet gravida. sed scelerisque mi ligula id porttitor ipsum faucibus et. etiam id ligula tortor. suspendisse potenti. morbi a vulputate massa. integer quis interdum erat sed maximus magna suspendisse tristique accumsan elit ut.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. duis iaculis sollicitudin turpis at sodales. nullam non risus eget elit molestie feugiat. integer ut lacus in turpis consectetur convallis nec a leo. curabitur at urna lorem. morbi porta nisl id nunc pretium finibus. pellentesque placerat erat vel accumsan ultrices. sed eu lorem ex. donec eu leo at nisl sollicitudin consequat ac sed sem. phasellus interdum sapien sed tortor porta rhoncus.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. fusce vulputate tortor finibus eleifend egestas. class aptent taciti sociosqu ad litora torquent per conubia nostra per inceptos himenaeos. dynamic nisl diam eget est pellentesque hendrerit. phasellus sed justo est. cras tempor finibus elementum. proin vel finibus massa. donec efficitur eget ante vitae varius. nullam ac mollis lectus. maecenas feugiat hendrerit nisi sit amet vestibulum ex eleifend id.', 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12', true, 3, 2),

(6, 'revolution de palais au barca cet ete', 'la direction barcelonaise prépare un dégraissage massif de son effectif afin de libérer de la masse salariale et de recruter deux joueurs majeurs ciblés de longue date.', 'lorem ipsum dolor sit amet consectetur adipiscing elit. suspendisse iaculis tincidunt lorem quis ultrices. nulla facilisi. morbi sed arcu nec ante molestie tempor. curabitur pretium ex vitae mi tempus imperdiet. aliquam elementum interdum ipsum id iaculis. donec interdum accumsan risus nec commodo. vestibulum nec nulla sed diam viverra dictum in pulvinar libero. curabitur molestie leo nec erat pretium semper. proin at justo at risus viverra finibus ac sit amet sem.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. nulla ac diam accumsan ligula tempor cursus ac eget ex. nam ut ante non arcu congue laoreet non id magna. morbi porta eleifend dictum. aliquam rhoncus ex sapien ut convallis arcu facilisis sed. integer ac tempor sem. sed fringilla tempor sem non finibus. nulla sit amet nulla elit. integer imperdiet id libero ut fringilla. etiam rhoncus sapien ipsum vitae feugiat felis viverra ut.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. ut scelerisque elit magna vitae placerat lorem molestie vitae. donec sit amet felis arcu. duis facilisis diam nulla eu consequat felis iaculis eu. integer ut eros lectus. ut rhoncus lectus at nibh maximus tincidunt. phasellus aliquet tellus ac lectus elementum non sollicitudin libero elementum. duis condimentum purus sapien id scelerisque metus cursus eu. sed a nunc facilisis purus suscipit varius eu elementum nibh.', 'https://images.unsplash.com/photo-1518063319789-7217e6706b04', true, 3, 1),

(7, 'lens renforce sa defense avec un international', 'les sang et or ont bouclé l arrivée d un défenseur central d expérience pour pallier les blessures et aborder sereinement la deuxième partie de saison reguliere.', 'lorem ipsum dolor sit amet consectetur adipiscing elit. ut luctus ex sed accumsan consequat. proin feugiat elit ac metus congue sit amet luctus eros molestie. sed tristique mi non neque tristique imperdiet. donec tempor finibus ante nec tempus. nulla rhoncus sem vitae purus efficitur aliquet. aenean vel lectus pellentesque tellus vulputate finibus. sed elementum nisl a sem interdum bibendum. fusce imperdiet leo ut turpis egestas ac convallis felis semper. nam eu feugiat justo.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. ut dictum urna tellus vel feugiat ante scelerisque interdum. donec congue arcu a felis facilisis ac tristique ante condimentum. cras ut diam in neque posuere condimentum. pellentesque id lorem sollicitudin ex rutrum tempor interdum ut lorem. integer in eros sed nisl ultrices finibus. donec scelerisque libero tellus vitae facilisis tortor tincidunt et. curabitur nisl sem bibendum quis tellus at finibus tristique sapien.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. morbi efficitur accumsan dui sed pretium. ut pretium leo non purus vehicula rhoncus. integer pellentesque iaculis turpis id condimentum. nam feugiat mollis nisl feugiat viverra. donec scelerisque tincidunt iaculis. curabitur non mi quis ipsum facilisis mattis sit amet quis felis. dynamic sit amet sapien quis urna luctus convallis id sed mi. sed ac tellus ut nunc tristique viverra elementum ut leo.', 'https://images.unsplash.com/photo-1489945052260-4f21c52268b9', true, 1, 2),

(8, 'la juventus cherche un second souffle au milieu', 'le club de turin multiplie les pistes pour dénicher un milieu créatif capable de redynamiser le jeu offensif de l équipe en perte de vitesse en championnat.', 'lorem ipsum dolor sit amet consectetur adipiscing elit. donec nec justo sed velit pretium placerat vitae at purus. quisque tincidunt lectus at lectus laoreet gravida. sed scelerisque mi ligula id porttitor ipsum faucibus et. etiam id ligula tortor. suspendisse potenti. morbi a vulputate massa. integer quis interdum erat sed maximus magna suspendisse tristique accumsan elit ut. aliquam elementum interdum ipsum id iaculis.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. duis iaculis sollicitudin turpis at sodales. nullam non risus eget elit molestie feugiat. integer ut lacus in turpis consectetur convallis nec a leo. curabitur at urna lorem. morbi porta nisl id nunc pretium finibus. pellentesque placerat erat vel accumsan ultrices. sed eu lorem ex. donec eu leo at nisl sollicitudin consequat ac sed sem. phasellus interdum sapien sed tortor porta rhoncus.\n\nlorem ipsum dolor sit amet consectetur adipiscing elit. ut scelerisque elit magna vitae placerat lorem molestie vitae. donec sit amet felis arcu. duis facilisis diam nulla eu consequat felis iaculis eu. integer ut eros lectus. ut rhoncus lectus at nibh maximus tincidunt. phasellus aliquet tellus ac lectus elementum non sollicitudin libero elementum. duis condimentum purus sapien id scelerisque metus cursus eu. sed a nunc facilisis purus suscipit varius eu elementum nibh.', 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af', true, 3, 2);